# Generated by Django 3.2.5 on 2021-08-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_network_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='descripcion',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
